pipeline{
    agent any

    stages{
        stage('Getting latest image from listolet branch'){
            steps{
                git branch: 'listolet', url: 'https://github.com/alamhamim/qa_library_selenium.git'
            }
        }
        stage('Running the test cases'){
            steps{
                bat 'mvn clean test -DsuiteXmlFile=suites/runner.xml'
            }
        }
        stage('Publishing HTML REPORT (LISTOLET)'){
            steps {
                publishHTML([allowMissing: true, alwaysLinkToLastBuild: true, keepAll: false, reportDir: '/Report', reportFiles: 'report_*.html', reportName: 'LISTOLET Report', reportTitles: 'Test Report'])
            }
        }
        stage('Email Report to Job Owner') {
            steps {
                emailext (
                    subject: "Listolet Test Report",
                    body: "Please see attached report",
                    attachmentsPattern: "**/Report/report_*.html",
                    to: "hamim.alam.personal@gmail.com"
                )
            }
        }
    }
}
